{"owner":{"reputation":2951,"user_id":22836,"user_type":"registered","accept_rate":79,"profile_image":"https://i.stack.imgur.com/EmmZL.png?s=128&g=1","display_name":"4per","link":"https://ru.stackoverflow.com/users/22836/4per"},"is_accepted":false,"score":0,"last_activity_date":1535080436,"last_edit_date":1535080436,"creation_date":1535072085,"answer_id":872769,"question_id":872684,"body":"<p>Подпишитесь на <code>Application.ThreadException</code></p>\n\n<p>Исключения из ГУИ-потока так ловятся. А вот исключения из прочих потоков, просто крашат приложение, поэтому их пришлось завернуть в <code>try-catch</code> все.</p>\n"}